# Generated by Django 5.1.7 on 2025-03-21 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0002_boat_manufactor_boat_model_boat_year_built_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='share_owner_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_owner_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boat',
            name='share_owner_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_owner_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boat',
            name='share_owner_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_owner_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boat',
            name='share_owner_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_owner_4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boat',
            name='share_owner_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_owner_5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boat',
            name='share_owner_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_owner_6', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boat',
            name='share_owner_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_owner_7', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boat',
            name='share_owner_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_owner_8', to=settings.AUTH_USER_MODEL),
        ),
    ]
