# Generated by Django 5.1.7 on 2025-03-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0003_boat_share_owner_1_boat_share_owner_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='owner',
        ),
        migrations.DeleteModel(
            name='BoatsOwners',
        ),
    ]
