# Generated by Django 5.1.7 on 2025-03-23 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0004_remove_boat_owner_delete_boatsowners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='manufactor',
        ),
        migrations.AddField(
            model_name='boat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boat',
            name='manufacturer',
            field=models.CharField(choices=[('Fast', 'Fast'), ('Delta', 'Delta'), ('Beneteau', 'Beneteau'), ('Jenneau', 'Jenneau')], default='Fast', max_length=64, verbose_name='manufacturer'),
        ),
        migrations.AddField(
            model_name='boat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='number_shares',
            field=models.PositiveIntegerField(default=8, verbose_name='number of shares'),
        ),
    ]
