# Generated by Django 5.2 on 2025-04-09 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0006_alter_boat_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boat_items', to='boat.boat')),
            ],
        ),
        migrations.DeleteModel(
            name='BoatSection',
        ),
    ]
