# Generated by Django 5.2 on 2025-04-09 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0007_boatitems_delete_boatsection'),
        ('occurrence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boat_items', to='occurrence.item'),
        ),
        migrations.AddField(
            model_name='boat',
            name='items',
            field=models.ManyToManyField(through='boat.BoatItems', to='occurrence.item', verbose_name='items'),
        ),
    ]
