# Generated by Django 5.2 on 2025-04-17 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0009_rename_boatitems_boatitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='name',
            field=models.CharField(default='Unnamed Boat', max_length=64, unique=True, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='UserReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boat.boat', verbose_name='boat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='boat',
            name='users_for_reminders',
            field=models.ManyToManyField(through='boat.UserReminder', to=settings.AUTH_USER_MODEL, verbose_name='users for reminders'),
        ),
    ]
