# Generated by Django 5.2 on 2025-04-17 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0010_alter_boat_name_userreminder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReminder',
            new_name='UsersNotification',
        ),
        migrations.RemoveField(
            model_name='boat',
            name='users_for_reminders',
        ),
        migrations.AddField(
            model_name='boat',
            name='users_notification',
            field=models.ManyToManyField(through='boat.UsersNotification', to=settings.AUTH_USER_MODEL, verbose_name='users for notifications'),
        ),
    ]
