# Generated by Django 5.2 on 2025-04-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0011_rename_userreminder_usersnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='name'),
        ),
    ]
