# Generated by Django 5.1.7 on 2025-03-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('phone', models.CharField(max_length=16, verbose_name='cell phone')),
                ('email', models.EmailField(max_length=256, verbose_name='email')),
                ('speciality', models.CharField(choices=[('EN', 'Engineering'), ('PL', 'Plumbing'), ('EL', 'Electrical'), ('ME', 'Mechanical'), ('HY', 'Hydraulics'), ('CA', 'Carpentry'), ('SA', 'Safety'), ('PA', 'Painting'), ('OT', 'Other')], max_length=2, verbose_name='speciality')),
            ],
        ),
    ]
