# Generated by Django 5.1.7 on 2025-03-23 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='speciality',
            field=models.CharField(choices=[('EN', 'Engineering'), ('PL', 'Plumbing'), ('EL', 'Electrical'), ('ME', 'Mechanical'), ('HY', 'Hydraulics'), ('CA', 'Carpentry'), ('SA', 'Safety'), ('PA', 'Painting'), ('OT', 'Other')], default='EN', max_length=2, verbose_name='speciality'),
        ),
    ]
