# Generated by Django 5.2 on 2025-04-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0003_alter_technician_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='company',
            field=models.CharField(blank=True, max_length=64, verbose_name='company'),
        ),
    ]
