# Generated by Django 5.2 on 2025-04-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0004_technician_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='company',
            field=models.CharField(default='Autônomo', max_length=64, verbose_name='company'),
        ),
    ]
