# Generated by Django 5.2 on 2025-04-09 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boat', '0007_boatitems_delete_boatsection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('sector', models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electric'), ('EQ', 'equipment'), ('CA', 'cables'), ('RI', 'rigging'), ('OT', 'other')], default='EN', max_length=2, verbose_name='sector')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('engine_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='engine hours')),
                ('obs', models.TextField(blank=True, verbose_name='observation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boat.boat', verbose_name='boat')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ok', models.BooleanField(default=True, verbose_name='is ok')),
                ('obs', models.TextField(blank=True, verbose_name='observation')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrence.checkout', verbose_name='checkout')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrence.item', verbose_name='item')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='items',
            field=models.ManyToManyField(through='occurrence.CheckoutItems', to='occurrence.item', verbose_name='items'),
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, verbose_name='description')),
                ('date', models.DateField(verbose_name='date')),
                ('sector', models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electric'), ('EQ', 'equipment'), ('CA', 'cables'), ('RI', 'rigging'), ('OT', 'other')], default='EN', max_length=2, verbose_name='sector')),
                ('observation', models.TextField(blank=True, verbose_name='observation')),
                ('engine_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='engine hours')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boat.boat', verbose_name='boat')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
    ]
