# Generated by Django 5.2 on 2025-04-09 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckoutItems',
            new_name='CheckoutItem',
        ),
    ]
