# Generated by Django 5.2 on 2025-04-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0002_rename_checkoutitems_checkoutitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sector',
            field=models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electric'), ('EQ', 'equipment'), ('ET', 'electronic'), ('CA', 'cables'), ('RI', 'rigging'), ('SA', 'sail'), ('OT', 'other')], default='EN', max_length=2, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='sector',
            field=models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electric'), ('EQ', 'equipment'), ('ET', 'electronic'), ('CA', 'cables'), ('RI', 'rigging'), ('SA', 'sail'), ('OT', 'other')], default='EN', max_length=2, verbose_name='sector'),
        ),
    ]
