# Generated by Django 5.2 on 2025-04-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0003_alter_item_sector_alter_occurrence_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sector',
            field=models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electric'), ('KI', 'kitchen'), ('ET', 'electronic'), ('CA', 'cables'), ('RI', 'rigging'), ('SA', 'sail'), ('CO', 'confort'), ('OT', 'other')], default='EN', max_length=2, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='sector',
            field=models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electric'), ('KI', 'kitchen'), ('ET', 'electronic'), ('CA', 'cables'), ('RI', 'rigging'), ('SA', 'sail'), ('CO', 'confort'), ('OT', 'other')], default='EN', max_length=2, verbose_name='sector'),
        ),
    ]
