# Generated by Django 5.2 on 2025-04-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0004_alter_item_name_alter_item_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sector',
            field=models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electric'), ('KI', 'kitchen'), ('ET', 'electronic'), ('CA', 'cables'), ('RI', 'rigging'), ('SA', 'sail'), ('EQ', 'equipment'), ('CO', 'confort'), ('OT', 'other')], default='EN', max_length=2, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='sector',
            field=models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electric'), ('KI', 'kitchen'), ('ET', 'electronic'), ('CA', 'cables'), ('RI', 'rigging'), ('SA', 'sail'), ('EQ', 'equipment'), ('CO', 'confort'), ('OT', 'other')], default='EN', max_length=2, verbose_name='sector'),
        ),
    ]
