# Generated by Django 5.2 on 2025-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0005_alter_item_sector_alter_occurrence_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='observation',
            new_name='obs',
        ),
        migrations.AlterField(
            model_name='item',
            name='sector',
            field=models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electrical'), ('ET', 'electronics'), ('EQ', 'equipments'), ('CA', 'cables'), ('SA', 'sails'), ('RI', 'rigging'), ('KI', 'kitchen'), ('LG', 'lounge'), ('CB', 'cabin'), ('DE', 'deck'), ('CP', 'cockpit'), ('FU', 'fun')], default='EN', max_length=2, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='sector',
            field=models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electrical'), ('ET', 'electronics'), ('EQ', 'equipments'), ('CA', 'cables'), ('SA', 'sails'), ('RI', 'rigging'), ('KI', 'kitchen'), ('LG', 'lounge'), ('CB', 'cabin'), ('DE', 'deck'), ('CP', 'cockpit'), ('FU', 'fun')], default='EN', max_length=2, verbose_name='sector'),
        ),
    ]
