# Generated by Django 5.2 on 2025-04-22 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_alter_maintenance_sector_alter_periodic_sector'),
        ('occurrence', '0006_rename_observation_occurrence_obs_alter_item_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.maintenance', verbose_name='maintenance'),
        ),
    ]
