# Generated by Django 5.2 on 2025-05-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0007_occurrence_maintenance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='engine_hours',
            new_name='hour_meter',
        ),
        migrations.RenameField(
            model_name='occurrence',
            old_name='engine_hours',
            new_name='hour_meter',
        ),
    ]
