# Generated by Django 5.2 on 2025-05-02 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0012_alter_boat_name'),
        ('occurrence', '0008_rename_engine_hours_checkout_hour_meter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='hour_meter',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='hour meter'),
        ),
        migrations.RenameModel(
            old_name='CheckoutItem',
            new_name='CheckInOutItem',
        ),
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(verbose_name='date')),
                ('checkin_hour_meter', models.PositiveIntegerField(blank=True, null=True, verbose_name='hour meter')),
                ('checkin_obs', models.TextField(blank=True, verbose_name='observation')),
                ('checkout_date', models.DateField(verbose_name='date')),
                ('checkout_hour_meter', models.PositiveIntegerField(blank=True, null=True, verbose_name='hour meter')),
                ('checkout_obs', models.TextField(blank=True, verbose_name='observation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boat.boat', verbose_name='boat')),
                ('checkout_items', models.ManyToManyField(through='occurrence.CheckInOutItem', to='occurrence.item', verbose_name='items')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
        migrations.AlterField(
            model_name='checkinoutitem',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='occurrence.checkinout', verbose_name='checkout'),
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
