# Generated by Django 5.2 on 2025-05-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence', '0009_alter_occurrence_hour_meter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='checkin_hour_meter',
            field=models.PositiveIntegerField(default=0, verbose_name='hour meter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='checkout_date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
    ]
