# Generated by Django 5.1.7 on 2025-03-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='sector',
            field=models.CharField(choices=[('MT', 'Motor'), ('HY', 'Hydraulic'), ('EL', 'Electrical'), ('CA', 'Cables'), ('RI', 'Rigging'), ('OT', 'Other')], default='MT', max_length=2, verbose_name='sector'),
        ),
    ]
