# Generated by Django 5.1.7 on 2025-03-25 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0005_remove_boat_manufactor_boat_created_at_and_more'),
        ('maintenance', '0002_maintenance_sector'),
        ('technician', '0003_alter_technician_speciality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boat.boat', verbose_name='boat'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='sector',
            field=models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electric'), ('EQ', 'equipment'), ('CA', 'cables'), ('RI', 'rigging'), ('OT', 'other')], default='EN', max_length=2, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='technician.technician', verbose_name='technician'),
        ),
    ]
