# Generated by Django 5.1.7 on 2025-03-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenance_engine_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64, verbose_name='description')),
                ('periodicity', models.CharField(choices=[('WE', 'weekly'), ('BW', 'bi-weekly'), ('MO', 'monthly'), ('QU', 'quarterly'), ('SA', 'semi-annually'), ('AN', 'annually')], default='MO', max_length=2, verbose_name='periodicity')),
                ('periodicity_day', models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], null=True, verbose_name='periodicity day')),
                ('periodicity_month', models.PositiveIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, verbose_name='periodicity month')),
                ('periodicity_week_day', models.PositiveIntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True, verbose_name='periodicity week day')),
                ('periodicity_value', models.PositiveIntegerField(verbose_name='periodicity value')),
                ('last_run_date', models.DateField(blank=True, null=True, verbose_name='last run date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
    ]
