# Generated by Django 5.1.7 on 2025-03-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_periodic_delete_perido'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodic',
            name='sector',
            field=models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electric'), ('EQ', 'equipment'), ('CA', 'cables'), ('RI', 'rigging'), ('OT', 'other')], default='EN', max_length=2, verbose_name='sector'),
        ),
    ]
