# Generated by Django 5.1.7 on 2025-04-01 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_maintenance_periodic_alter_periodic_periodicity_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='periodic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.periodic', verbose_name='periodic'),
        ),
    ]
