# Generated by Django 5.1.7 on 2025-04-01 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_alter_maintenance_periodic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='periodic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.periodic', verbose_name='periodic'),
        ),
    ]
