# Generated by Django 5.1.7 on 2025-04-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_alter_maintenance_periodic'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='value'),
        ),
    ]
