# Generated by Django 5.2 on 2025-04-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_alter_maintenance_periodic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='observation',
            new_name='obs',
        ),
    ]
