# Generated by Django 5.2 on 2025-04-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_alter_maintenance_sector_alter_periodic_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='sector',
            field=models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electric'), ('KI', 'kitchen'), ('ET', 'electronic'), ('CA', 'cables'), ('RI', 'rigging'), ('SA', 'sail'), ('CO', 'confort'), ('OT', 'other')], default='EN', max_length=2, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='periodic',
            name='sector',
            field=models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electric'), ('KI', 'kitchen'), ('ET', 'electronic'), ('CA', 'cables'), ('RI', 'rigging'), ('SA', 'sail'), ('CO', 'confort'), ('OT', 'other')], default='EN', max_length=2, verbose_name='sector'),
        ),
    ]
