# Generated by Django 5.2 on 2025-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_alter_maintenance_sector_alter_periodic_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='sector',
            field=models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electrical'), ('ET', 'electronics'), ('EQ', 'equipments'), ('CA', 'cables'), ('SA', 'sails'), ('RI', 'rigging'), ('KI', 'kitchen'), ('LG', 'lounge'), ('CB', 'cabin'), ('DE', 'deck'), ('CP', 'cockpit'), ('FU', 'fun')], default='EN', max_length=2, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='periodic',
            name='sector',
            field=models.CharField(choices=[('EN', 'engine'), ('HY', 'hydraulic'), ('EL', 'electrical'), ('ET', 'electronics'), ('EQ', 'equipments'), ('CA', 'cables'), ('SA', 'sails'), ('RI', 'rigging'), ('KI', 'kitchen'), ('LG', 'lounge'), ('CB', 'cabin'), ('DE', 'deck'), ('CP', 'cockpit'), ('FU', 'fun')], default='EN', max_length=2, verbose_name='sector'),
        ),
    ]
