# Generated by Django 5.2 on 2025-05-01 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_alter_maintenance_sector_alter_periodic_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='engine_hours',
            new_name='hour_meter',
        ),
    ]
