# Generated by Django 5.2 on 2025-05-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_rename_engine_hours_maintenance_hour_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='hour_meter',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='hour meter'),
        ),
    ]
