# Generated by Django 5.1.7 on 2025-03-20 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='profiles/')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='address')),
                ('state', models.CharField(blank=True, max_length=64, verbose_name='state')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='country')),
                ('zip_code', models.CharField(blank=True, max_length=16, verbose_name='zip code')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
