name: Production Deploy with GIT

on:
    workflow_dispatch:

jobs:
    # deploy de Desenvolvimento
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: boat
            url: http://hgf777.net.br
        steps:
            - name: Repository Checkout
              uses: actions/checkout@v4
            - name: Development Deploy
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{vars.REMOTE_HOST}}
                username: ${{vars.REMOTE_USER}}
                password: ${{secrets.PASSWORD}}
                port: ${{vars.REMOTE_PORT}}
                script: |
                  cd boat_maintenance
                  git pull
                  cp "envs/.env" ".env"
                  sudo docker compose down
                  sudo docker compose up --build -d
